### ISSUE TITLE
Ability to launch more than one app on connect

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jroal/a2dpvolume#181]
```
This feature would be really interesting for car driving i.e. launching both 
navigation and radio app.

Best regards.
```

Original issue reported on code.google.com by `patrice....@gmail.com` on 15 Jan 2014 at 2:37

**Comment by jroal** [comment]
This is a job for Automate or Tasker.  I am going to call this out of scope as I am limiting changes on this app now to just maintain functionality to support new Android versions (which is work enough).
