### ISSUE TITLE
LG G4 quiet phone call audio

### ISSUE THREAD

**Issue by rdolishny** [jroal/a2dpvolume#200]
First of all thank you for all of this documentation. It's appreciated. 

I have 3 phones and only my new LG G4 vigor has quiet bt voice volume. Callers hear me fine, I can't really hear them. 

All other audio is loud and clear. Streaming audio. Notifications.  

Does your app boost audio like this? After installing it I can't bot ice a difference in any audio... Even when I turn it all the way down. Android 5.5.1

Thanks!

**Comment by jroal** [comment]
My app does not boost any volume. It just adjusts it to max. I think there are apps for that though.


http://jimroal.com






On Wed, Nov 18, 2015 at 5:32 AM -0800, "Rick Dolishny" <notifications@github.com> wrote:












First of all thank you for all of this documentation. It's appreciated. 



I have 3 phones and only my new LG G4 vigor has quiet bt voice volume. Callers hear me fine, I can't really hear them. 



All other audio is loud and clear. Streaming audio. Notifications.  



Does your app boost audio like this? After installing it I can't bot ice a difference in any audio... Even when I turn it all the way down. Android 5.5.1



Thanks!
