### ISSUE TITLE
Loud volume warning message blocks volume adjustment

### ISSUE THREAD

**Issue by jroal** [jroal/a2dpvolume#202]
This has been an issue all along but there may be hope.  I found this recently: https://gerrit.omnirom.org/#/c/5203/3/src/com/android/settings/SoundSettings.java

Notice this:

Max Weninger
here the default is 0 - please compare to your base part :)Jan 29, 2014
Max Weninger
Jan 30, 2014
The default value must be 1 - checked means - show volume warning
See also my  comment to the base change. MANUAL_SAFE_MEDIA_VOLUME is a little bit confusing. I would assume something named "manual" to overrule the default if it is true

        } else if (preference == mVolumeWarning) {
            int volumeWarning = (Boolean) objValue ? 1 : 0;
            Settings.System.putInt(getContentResolver(),
                    Settings.System.MANUAL_SAFE_MEDIA_VOLUME, volumeWarning);

It appears there is a way to disable the warning message with this call .  They may be fishing for a fix here but it looks promising.

**Comment by ExSport** [comment]
If it will ever work post donate button please😃
If it will ever work also on Android v4.2.1 it will be double great.
Unfortunately I read somewhere this project is abandoned?😞

**Comment by jroal** [comment]
This project is not abandoned but it is also not a high priority of mine.  When I get time I work on it some.  Right now I have much higher issues to work on this project.  If someone would like to work these issues, great.

**Comment by jroal** [comment]
I noticed on my 2015 Moto-X this is no longer an issue.  My hope is they fixed this in Android 6.0 and up.  Maybe even earlier.  I could not find a way to fix this anyway.
