### ISSUE TITLE
Add app/build.gradle file to repo

### ISSUE THREAD

**Issue by krt16s** [jroal/a2dpvolume#203]
The project is missing `app/build.gradle` file which should contain all dependencies etc. A clean checkout doesn’t not build (maybe AndroidStudio can import it an generate build.gradle on the fly, but running gradle from CLI does not do that).

**Comment by jroal** [comment]
The build.gradle file contains information about the keystore so it is ignored.  Here are the parts of it you need.

apply plugin: 'com.android.application'
android {
    signingConfigs {
        config {

        }
    }
    compileSdkVersion 19
    buildToolsVersion '23.0.2'
    defaultConfig {
        applicationId "a2dp.Vol"
        minSdkVersion 15
        targetSdkVersion 19
    }
    buildTypes {

    }
    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
        }
    }
}

dependencies {
    compile 'com.android.support:support-v4:21.0.3'
}

**Comment by krt16s** [comment]
Thanks for the quick reply. Is there any option to push the braebone gradle file without the singing config to the repo? Just in case you plan to add/update support libs etc...

**Comment by jroal** [comment]
I have not figure out how yet.  Maybe when I get more time I will look into it.  I am not a git expert by any means.
