### ISSUE TITLE
Does not read mms (group) texts on Xperia Z3C running Android 5.1.1

### ISSUE THREAD

**Issue by rknobbe** [jroal/a2dpvolume#204]
SMS notifications read out fine over bluetooth. MMS (group texts) don't read out at all.

**Comment by jroal** [comment]
This is issue 197

**Comment by jroal** [comment]
I am not working MMS separately. I intend to abandon the old sms reader and just use the notification reader, once I get it working on lollipop and up. Could be a while though as I am working this alone as a hobby. Anyone want to help?
