### ISSUE TITLE
bluetooth

### ISSUE THREAD

**Issue by bottrw** [jroal/a2dpvolume#217]
in a 2013 Honda Civic I can writee texts through Bluetooth,it works perfect, reads my text back to me and sends.  the problem is I don't receive texts thru Bluetooth, when the text comes in my radio goes off but no text, nothing, just silence.  seems really strange works outgoing but not incoming. I'm use Samsung galaxy amp prime, Android 6.0.1

**Comment by jroal** [comment]
It sounds like you are using some other app/car feature.  Is there a question in this issue?  If you are using A2DP Volume, have you read the manual https://github.com/jroal/a2dpvolume/wiki and configured your device properly?  My app does not handle writing texts so it sounds like a feature of your car may not be working right.  This forum is only for A2DP Volume issues.  If you are having issues with my app reading texts, please read this: https://github.com/jroal/a2dpvolume/wiki/Reading-Messages

Unless I get some info that says my app has an issue, I will close this thread in a couple days.
