### ISSUE TITLE
Wiki update - typo for older Android versions

### ISSUE THREAD

**Issue by clach04** [jroal/a2dpvolume#219]
I couldn't see a way to contribute wiki updates so cloned/branched/updated wiki into https://github.com/clach04/a2dpvolume_wiki/tree/version_log_typo

I noticed there are no releases https://github.com/jroal/a2dpvolume/releases so  was not able to link to an APK for version 2.11.13

**Comment by jroal** [comment]
I'm not sure what to do with this.  I have made several edits to the documentation now.  Merging this back in would take some work.  If the edits were small, it would have been best to just explain that in the issue.  If there were bigger changes, then a pull request would work.  

Good point on the releases.  I need to learn how to do that and start using it properly.
