### ISSUE TITLE
Connect with Media audio 

### ISSUE THREAD

**Issue by S6Sam** [jroal/a2dpvolume#220]
When connects to a Bluetooth device, is it possible to force the Media audio also to be transferred to the connected device like in your previous versions?

**Comment by jroal** [comment]
This is not possible to my knowledge.  The volume adjustment behavior has not changed for a very long time.  It was never able to change the volume on the receiving device.

**Comment by jroal** [comment]
Fixed in 2.12.5.  Was confused by comment.  Presume actually referred to Bluetooth connect feature whcih was actually broken.
