### ISSUE TITLE
Add option to enable GPS while connected to BT device

### ISSUE THREAD

**Issue by nbarion** [jroal/a2dpvolume#226]
Hello! Great app!!  Very useful. I suggest with the option to connect to a Bluetooth device, put an option to enable the GPS tracking from the phone too (for example,  when I connect the Bluetooth car, turn on the phone GPS and open the anti radar/ GPS app/ etc). Thank you!

**Comment by jroal** [comment]
Here is some discussion on the topic of programmatically enabling GPS: http://stackoverflow.com/questions/4721449/how-can-i-enable-or-disable-the-gps-programmatically-on-android
Basically, it can possibly be done with a hack.  This is not something I want in my app as it can be considered a security problem.
