### ISSUE TITLE
Custom Names of Paired Bluetooth Devices not displayed

### ISSUE THREAD

**Issue by jpshupe** [jroal/a2dpvolume#230]
In Android Settings > Bluetooth, you can edit the name of your paired devices to give them a custom name. These names aren't showing up in A2DP Volume. Instead, what shows up is the default name for each device.

Notes:
*Device: Google Pixel XL
*OS: Android 7.1.1
*Special Circumstances: I have two identical devices paired to my phone (they're bluetooth car audio adapters and I have one in each car). When originally paired, they displayed the same name (the product's model number). I renamed them in Android and then noticed those custom names didn't translate into A2DP Volume.

**Comment by jroal** [comment]
Yeah, I had this working at one time but something happened in Android and broke it again.  Valid issue but I have not had the time to fix it.  I will keep it here so I can work it if/when I get some time.  Anyone else want to help out?

**Comment by jroal** [comment]
I think I have fixed this in 2.12.9.  I implemented a call to the method to getAlias.  Tested on a 4.4 device and it seems to work.
