### ISSUE TITLE
If additional BT devices are paired after A2DP was installed, A2DP Volume stops controlling volume correctly for existing devices.

### ISSUE THREAD

**Issue by jpshupe** [jroal/a2dpvolume#231]
Here's the order of events:
1) Pair 3 BT devices (Headset, Daydream Remote, Car Audio adapter)
2) Install A2DP Volume
3) Configure A2DP Volume to set volume to max whenever Car Audio adapter connects. (Yes Ramped, 2s Delay, Do not restore previous volume)
*At this point, everything is working as expected. BT Card Audio device connects and the app sets the volume as configured
4) Pair a 4th BT Device (another Car Audio adapter, identical to the first)
5) Setup the 4th BT Device in A2DP Volume & configure it the same as the other device.
*At this point, neither car A2DP Volume is not responding correctly to either BT Device (they were never powered up at the same time). For both devices, the volume would be set to about half of full volume (Full Volume was specified in the app settings). Also, if you manually changed the volume up, it would be magically lowered back down, but never to the same value.
6) Try changing settings for the BT Devices (Delay? Ramp? Volume to use? Restore last volume used) and stopping/restarting the A2DP Volume service. 
*Issue persists
7) Uninstall and re-install A2DP Volume. Re-configure settings for both BT Car Audio devices (same settings as before).
*Fixed!

Notes:
*Android 7.1.1
*Google Pixel XL

**Comment by djasonpenney** [comment]
Confirmed.  VZW Samsung Galaxy 7 Edge, Android 7.0

**Comment by jroal** [comment]
Some devices have features that also try to manage the volume with BT connected.  When this happens, add more delay for A2DP Volume to make the adjustment.  I have seen this before where A2DP Volume will make the adjustment but then another app or device feature will adjust the volume again.  

Also, make sure you do not use the "remember last used volume on disconnect".  I should just remove that as too many times the BT devices will go through more than one connect/disconnect cycles while connecting and it will mess with this. 

I have not had time to investigate this further.  I will leave this issue active and look into it when I have time.  Thanks for reporting.

**Comment by jroal** [comment]
I was not able to verify this but I have now made numerous changes that may have fixed this.  I will close this now.  If it happens in 2.12.10.2 or higher let me know.
