### ISSUE TITLE
Translations needed for 2.12.9 permissions handling

### ISSUE THREAD

**Issue by jroal** [jroal/a2dpvolume#237]
Translations needed for Android 6.0 permission handling.  Several new dialogs were introduced to handle permissions in Android 6.0 and up.  These require translations.
![image](https://cloud.githubusercontent.com/assets/893554/21965956/7e1d2b50-db2f-11e6-8754-f1e3d85fce1c.png)

The ask* (except askSetPerm) key strings are for explaining to the user what the permissions is needed for.  askSetPerm is the button text in the common dialog box that pops up to request a permission. 

needStorage is only used in the ManageData class in the cause no external storage is reachable.  It is in a very old Toast message but I thought it was time to make it more useful.

Android Studio now has a nice translations tool.  You can open up strings.xml and up in the top right a link to the translation editor is shown.  Click that to open the translations editor.  At the top left you will see "Show only keys needing translations".  Check that and you will see the missing ones where you can fill them in.

**Comment by uschindler** [comment]
Will look into it.

Uwe

**Comment by jroal** [comment]
I am wanting to release this as it is important the handle permissions in Android 6 and higher.  I know this is all volunteer work but it is also only 7 strings.  If I don't get these translated in the next few weeks I may publish the update without them, or use Google translate.

**Comment by sle118** [comment]
Added pull request #239  

Also, noticed a couple of typos in the original English string

    <string name="askLocation">The app needs to access location data to **_stoere_** location when device disconnects.</string>
    <string name="askContacts">The app needs access to your **_contects_** to

**Comment by uschindler** [comment]
Sorry for delay, I added the translations for German.

**Comment by jroal** [comment]
Thanks sle118 and uschindler!  Appreciate the help.  

Now waiting on Danish and Japanese.

**Comment by sle118** [comment]
Thank you for your patience!  I'm quite busy these days but managed to remember to do this when I had the bandwidth!

**Comment by jroal** [comment]
I have French and German done now.  If I don't get the other languages done soon I will just remove them completely.  I can't wait forever.  Sorry.  I need Japanese, Danish, and Greek done asap.  The current version on Android 6 and up will just crash anytime an expected permission is not granted.  Right now you have to manually grant them.  This is a big problem I need to resolve asap.

**Comment by sle118** [comment]
I suggest you go with auto translate. Not really the best, but could get you there until translations are figured out!

Télécharger Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by jroal** [comment]
I only got French and German updates.  The rest are missing the new translated strings so people will see English on those.  Had to release anyway.  Given the problems I had with auto-translations in the past, I will not do that here especially since many of these strings are long.
