### ISSUE TITLE
Service seems to be restarting quite often 

### ISSUE THREAD

**Issue by Wh1rledPeas** [jroal/a2dpvolume#238]
Starting a few weeks ago, I started getting "service starting" notices while just using my phone around my house.

I have no idea why this is occurring and have not been able to coordinate this behavior with anything else that might be going on at that time. 

Samsung Galaxy S5
Android v6.0.1

**Comment by jroal** [comment]
Check this wiki: https://github.com/jroal/a2dpvolume/wiki/Tips for app crashes.  Make sure you give the app all permissions.  I am working on fixing the Amdroid 6 permissions but until I get that out, you will need to go at Android settings -> apps -> A2DP Volume and then permissions.  Turn them all ON.  

Other things can also cause this.  If you have the notification icon turned OFF it becomes much more likely the app will get killed to free up memory.

**Comment by Wh1rledPeas** [comment]
Thank you for the prompt response. I do have it set to show the icon in the
notification bar only when connected. That might be the problem.

I do know that A2DP does always seem to come alive when I get in my
vehicle, so it seems to be working. I think for now, I'll just turn off
notifications, so I'm not bothered by them.

I chose to only give access to location in the permissions, as I'm fairly
particular about what permissions I give out and that seemed to be the only
one that this application should need access to.  So far I haven't seen any
issues pop up regarding permissions.

**Comment by jroal** [comment]
The problem with the current version of the app is that it was crash if permissions are missing.  There will be no pop-up, it will just crash.  I am working on a next version that fixes this but the translations folks are taking forever.

**Comment by Wh1rledPeas** [comment]
No worries Jim.

I'm a retired software architect, so I completely understand. The app is
probably crashing behind the scenes, but turning off notifications allows
it to happen without me knowing. It does seem to continue restarting (hence
the "service starting" messages) and it always activates when I sync up
with my vehicle, so for now this is working for me.

My main reason for reporting wasn't to complain. Just making sure it was
identified and was on the fix-list. ;)
