### ISSUE TITLE
bluetooth settings swap on reboot

### ISSUE THREAD

**Issue by xicor333** [jroal/a2dpvolume#240]
If my phone reboots, the settings i have for my two bluetooth devices swap places. (i have my car at full volume and my headphones at half volume, they swap, putting the car at half volume and the headphones at full volume).

Also sometimes my car setting just goes to half volume and i cant figure out why that is.

**Comment by jroal** [comment]
Read this first: https://github.com/jroal/a2dpvolume/wiki/Tips

Make sure you put enough delay in the device connection to volume adjustment.  I find at least 6s is needed.  Make sure you don't have a pop-up blocking the volume adjustment as many devices do.  make sure you don't have another app also adjusting the volume is some OEM skins do.

Back to the volume swap thing.  Do you mean the settings are actually altered?  Of do you mean the volume adjustment does not match the settings?

**Comment by xicor333** [comment]
In both cases, the setting is actually getting altered. in one case, only my car setting was put at half volume, but in the reboot case, both of the settings actually swapped. In the app, it had the volume for car at half volume and the volume for my heaphones at full.

**Comment by jroal** [comment]
As it says in the tips, make sure you uncheck the "remember last used volume".  I should just remove that "feature" as it causes more harm than good.
