### ISSUE TITLE
IDEA: stats about played songs

### ISSUE THREAD

**Issue by mforbak** [jroal/a2dpvolume#241]
Just the idea, but when go to car, the music automatically starts to play by the player. But I have in the phone many songs, no time to sort or delete it manually. When driving, many time it is not possible to take the phone from the bag and delete the unwanted songs. So I just skip them on car bluetooth interface.

But it would be nice, if any app / player should create the stats about the played songs and when any song is skipped every time, it can offer me to delete this song from the device.

It is complicated, I love some interprets, but many interprets created 100 songs and only 5 are good for me. But no time to delete it...and every time skipping is also boring. I don't know, if it is possible to implement the described stats to your app, or this needs to be the functionality of music player?

**Comment by jroal** [comment]
I don't want to build a musing player into this app.  What you are talking about belongs in a music player app.
