### ISSUE TITLE
Provide pure floss build flavor

### ISSUE THREAD

**Issue by krt16s** [jroal/a2dpvolume#242]
Recently a non-free dependency, play-services / GoogleApiClient, has been added. Could you provide a build-flavor without that? This would require pushing `app/build.gradle` as well.

**Comment by jroal** [comment]
Sorry but I am plenty busy with this already.  You can always clone and do what you want.  Actually I am not even sure what the dependency is for and I don't recall adding it.

**Comment by jroal** [comment]
Actually this got me thinking so I did look into it.  I do not need that indexing service anyway so I did remove it in 2.12.9.2.  I will finish and push that soon.
