### ISSUE TITLE
"A2DP Stopped" after BT Disconnect

### ISSUE THREAD

**Issue by Hyperthread** [jroal/a2dpvolume#246]
After disabling Bluetooth, a white message box pops up, and states: "A2DP has stopped". It gives the option to"Close App" at the bottom of the white message box.

**Comment by jroal** [comment]
I have not been able to duplicate this issue.  What sequence of events happened?  Sounds like Bluetooth was enables and A2DV Volume was running.  Was the A2DP Volume UI open, or was the app running in the background?
