### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by xfire74** [jroal/a2dpvolume#248]
Hi,

I think I could prepare Polish translation. Contact me @ : emcom.it@gmail.com

BR,
Marcin

**Comment by jroal** [comment]
I have not planned any more releases of this app.  I may in the future but no plans now.  Here is the info on how to contribute to this free, open source app: https://github.com/jroal/a2dpvolume/wiki/Translations .  If you want to contribute free translations that website explains how.  This app has no revenue and therefore cannot support any costs.
