### ISSUE TITLE
A2DP repeat all messages 3 times

### ISSUE THREAD

**Issue by fbu78** [jroal/a2dpvolume#256]
HI !
Since I installed the application on my GS8, each SMS is repeated 3 times when I'm connected to my auto media.
 I have only one SMS application and I can not find anything in the parameters of A2DP that could influence this problem.
I use the last version 2.12.9.1 with : 
- enable SMS : 3 secondess
- voice call flow
- no driving mode sensibility

Precision : I have 2 BT connected at the same time (Gear S3 + auto media)

if you have an idea to solve this problem, I will be happy.
Thanks a lot
Fred

**Comment by jroal** [comment]
I have battled with this issue on Samsung for a long time.  I do have a thread here for this: https://github.com/jroal/a2dpvolume/wiki/Reading-Messages

Make sure you select reading SMS but then also make sure you don't read the notifications for the SMS app.  In other words, do one (read SMS) or the other (read notifications from the SMS app) but not both.  Also read this: https://github.com/jroal/a2dpvolume/wiki/Notification-Reader-Settings to understand the notification reader.

I don't have a Samsung device to test with so I don't know why those devices do this.  Make sure you do not add the smartwatch to the device list.  If it is there, delete is from the A2DP Volume devices list.  You don't want A2DP Volume responding to it.
