### ISSUE TITLE
A2DP Won't Release After TTS Has Finished Reading Out Message

### ISSUE THREAD

**Issue by rp188** [jroal/a2dpvolume#262]
Phone connected via Bluetooth with A2DP active. When listening to music over Bluetooth through the car, A2DP works and reads out my Whatsapp message, but at the end of the message the music doesn't resume. My car thinks the phone call is still active. I think there may be a bug where the app doesn't "hang up" after the message is read. To resume music playback I have to press end call on my car. After hanging up via the car it resumes the music. I am on the Google Pixel on 8.1, app version is 2.12.9.3.

**Comment by jook3d** [comment]
Hi, I have just got a Samsung S9+, running Android 8.0.0, A2DP version 2.12.9.3.  I suspect I have the same problem if you want any help with testing fixes.  Listening to a podcast via bluetooth earphones, the podcast will pause whilst the notification is read out, but it will then not resume playing again.

**Comment by jroal** [comment]
I added an attempted fix in 2.12.10.2.  Hopefully that fixes it.  I was not able to duplicate the issue and catch it happening.

**Comment by jroal** [comment]
I found an fixed many deeper issues and now believe I have a real fix for this.  The fix is included in 2.12.10.2 and up as I continue working on this release.
