### ISSUE TITLE
Translations needed please

### ISSUE THREAD

**Issue by jroal** [jroal/a2dpvolume#266]
Translations needed.   These strings need translations to all languages:

    <string name="needStorage">External storage not available</string>
    <string name="askPhone">Phone access is used to block the message reader while you are on a call.</string>
    <string name="askStorage">The app needs to be able to write data for stored location and to backup data.</string>
    <string name="askLocation">The app needs to access location data to stoere location when device disconnects.</string>
    <string name="askSms">The app needs to read SMS (text messages) to use the test message reading feature.</string>
    <string name="askContacts">The app needs access to your contects to tell who messages are from when reading messages.</string>
    <string name="askSetPerm">Set Permission</string>
    <string name="pushBtNamesButtonText">Push BT Names to Android</string>
    <string name="background_channel_name">A2DP Background</string>
    <string name="background_channel_description">Background</string>

    <string name="title_activity_location_viewer">Location Viewer</string>
    <string name="dummy_button">Dummy Button</string>
    <string name="dummy_content">DUMMY\nCONTENT</string>
    <string name="title_activity_loc_viewer">Location Viewer</string>
    <string name="foreground_channel_name" >A2DP Foreground</string>
    <string name="foreground_channel_description" >Foreground</string>

Use the strings resource file from the 2.12.10.1 release push to the repo.

**Comment by uschindler** [comment]
Hi, @jroal,
I am working on this, unfortunately I do not understand the meaning of those messages. What is a background/foreground channel. Could you send a screenshot of the english GUI?

**Comment by uschindler** [comment]
(sorry I am lost here, as I also have no idea where this is used!)

**Comment by jroal** [comment]
Oops.  More explanation is needed.  

Here is the foreground/background channel strings:
![](http://jimroal.com/A2DPScreens/NotificationConfig.png)
IN Android 8 and up these notifications are user configurable as to behavior.  

The permission strings (the ones that start with "ask") are needed for the new permissions introduced in Android 6: [https://developer.android.com/guide/topics/permissions/overview](https://developer.android.com/guide/topics/permissions/overview) where the user is asked to give ceertain permissions when they open the app.  

The needStorage string is just explaining to the user that external storage is not available.  

The pushBtNamesButtonText is for the button in the data screen that is used to push the names of BT devices that the user created in A2DP Volume back to Android Bluetooth settings.  

Hope that clarifies it.  Let me know if you still have questions.  Thanks for your help!

**Comment by uschindler** [comment]
OK, I added the German translations. I did not translate the "Dummy Button" and "DUMMY CONTENT". Is there anything needed or is this just a template for something new?

**Comment by uschindler** [comment]
Ah sorry, did not see your last message abozut the dummies. If you remove those "dummy" items, could you remove them from the german file, too?

**Comment by jroal** [comment]
@uschindler - Thanks!  I removed the dummy strings.  Thanks for your help.

**Comment by nabetaro** [comment]
Sorry. I kept you waiting.
I sent new PR:
https://github.com/jroal/a2dpvolume/pull/267

Please apply that.

**Comment by jroal** [comment]
> Sorry. I kept you waiting.
> I sent new PR:
> #267
> 
> Please apply that.

@nabetaro - I pulled the changes, thanks!
