### ISSUE TITLE
No way to disable notifications anymore

### ISSUE THREAD

**Issue by uschindler** [jroal/a2dpvolume#269]
With the latest Update, regardless of the setting to show/not show notifications on connect/disconnect, it still shows them always. There is no way to get rid of them from inside A2DP volume.

The only way to get rid of notifications is by disabling them completely for the A2DP volume app using the Android notification settings.

**Comment by jroal** [comment]
In Android 8.0 and up notifications can be managed to the users liking through the OS.  I need to just remove the setting actually.  There are now 2 "notification channels" and the user can configure how they work using the settings in the OS.  What I probably need to do is make a handy shortcut to open the OS notification settings for the app.

<whining> This app is starting to take too much work.  I am seriously considering just abandoning it as I don't have the time to keep it up. </whining>.  If you have some good ideas on how to make it more useful, I would happily take implemented code.  I will keep this issue on the list though and if/when I get some spare time I can look into it.  Thanks for posting.

**Comment by uschindler** [comment]
Ah okay. So the setting is just a relic. It's no problem, as I disabled notifications through Android already. Thanks.

**Comment by jroal** [comment]
Keep in mind that Android may stop apps that are running in the background without an active notification.  

By the way, I was able to configure the foreground channel to show the icon and the background channel to only show when you slide down from the top.  This is behavior people asked for years ago and now you can do it.  The background notification is enough to keep Android from stopping the app.

**Comment by uschindler** [comment]
Yeah, I know this. But it's easy to prevent this with recent Android. You can put apps on a list of app that should not be killed. See other issue #268. Works perfectly, notifications are not needed.

**Comment by jroal** [comment]
Here is the code in Service.java where the setting is overridden for API 25 and up.

```
// we will ignore the no notifications preference in API 25 and up since this can be managed
        // by the user now within Android
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N_MR1) notify = true;
```

**Comment by jroal** [comment]
Closing this since you can manage notifications in Android now.
