### ISSUE TITLE
Play Store policy change will remove SMS reading from apps like this

### ISSUE THREAD

**Issue by jroal** [jroal/a2dpvolume#274]
The Play Store has an new policy for apps that use permissions to read SMS (like this app).  If the app cannot be the default SMS app, the permission must be removed or the app will get removed from the Play Store.  This will kill the ability for A2DP Volume to read SMS.  If I just remove this feature, users can still read them through the notification reader by making their SMS app be in the list of apps to read messages from.  It would not be as good though since the notification reading is much messier and I would not be able to get the contact info.  Most SMS apps will put contact into in the notification so it would sorta work most of the time.  

I have come to a cross roads here.  The Play Store has become increasingly difficult to work with.  I am considering removing my apps from the Play Store.  This would mean people would have to side-load my apps if they want to continue using them.  I like the SMS reading feature and I don't want to remove it.  I also think it is just a matter of time before the Play Store finally just kills my app anyway.  I would like to hear feedback from you.

**Comment by cprhokie** [comment]
First of all thanks for this very useful application.  You have put a lot of time and effort into it and I really appreciate it.  
If and when they remove it from the play store you could then remove sms reading from the version that is in the play store, but keep it in a version that you provide for side loading.  I realize that it would be more work.  I still think there are a lot of useful features if the sms reading is removed.  
Google may also back down on some of these changes as they have for others because they can be genuinely useful to users.  
Finally... I would be happy to help maintain it or even take over if you ever decide you no longer have the time.

**Comment by jroal** [comment]
@cprhokie Thanks for the reply.  I did submit a request to the Play Store to keep SMS access.  I presume it will get denied but we will see.  I will say I am losing interest in maintaining this app especially as its features are finally getting implemented in Android (such as the primary volume management feature now being in Pie).    Tasker fills in most of the rest of the gaps.  I would happily take your help on this app in the open source project.  I have been hoping for years that more developers would start to get more involved and contribute.  So far I have had only had very spotty help on coding.  

Even if it goes away from the Play Store, I do plan to keep it going here in GitHub.  People would still be able to side load it.  I realize the user base would shrink significantly but that may not be all bad either.  

One other thought.  My code base is messy and getting very old.  Some of this code is 10 years old now and Android has changed a ton since then.  It would be really good to redo this whole app starting with a new project built to target the most current API.  It just seems like a ton of work but at some point it would be worth it I think.  There are ways to develop the app and make build variants which i have not learned how to do but that would enable the Play Store variant and a variant with SMS reader.    Another option would be to make the SMS reader a plugin.  They the main app can be on the Play Store and users wanting the SMS reader can just side load the plugin.

**Comment by jroal** [comment]
Awesome!  I am happy to take any help you are willing to give.  Maybe the rewrite is mostly replacing the main class and some cleanup of the service class as well as pulling the SMS out as a plugin.  Take a look at the code.  I made a broadcast receiver for reading out messages already so it should be fairly simple to pull out the SMS reader into its own app..  If you are willing to manage the F-Droid thing then great.

**Comment by cprhokie** [comment]
Sounds good.

**Comment by jroal** [comment]
Just pushed 2.12.11 which removes the SMS features.  The notification reader is still there and it can be used for SMS reading through the default SMS app notifications.
