### ISSUE TITLE
Volume still being adjusted despite app has been uninstalled from my phone

### ISSUE THREAD

**Issue by Shadertheboi** [jroal/a2dpvolume#280]
I've been doing a lot of investigation and research for days and finally realized that this app was the one behind this. why is my volume still being adjusted whenever my device is connected via bluetooth despite me already uninstalling this app? Before I uninstalled this app, I stopped the service and delete all bluetooth profiles created. But when I have this app installed and my profiles intact, this issue does not exist. Please assist. Thanks.

**Comment by jroal** [comment]
Do you have Android 9 (pie)?  If so, Android 9 does this now.  My app cannot do anything when it is uninstalled.
