### ISSUE TITLE
String translations needed for 2.13.0.0

### ISSUE THREAD

**Issue by jroal** [jroal/a2dpvolume#281]
I integrated A2DP Connect2 widget into A2DP Volume.  I now need these strings translated:

 <string name="storeloc_channel_name">A2DP Storing Location</string>
This is the name of the notification channel shown when A2DP Volume is storing a location after disconnect.

    <string name="storeloc_channel_desc">Location Storage</string>
This is the description of above.

    <string name="storing_location">Storing Location</string>
This seems redundant right now so it can be the same as the first.

    <string name="appwidget_text">Connect</string>
This is the text shown in the Android widget selector screen.  It labels the widget.  This is for the new connect widget.

    <string name="configure">Configure</string>
Just a description of configuring the widget.

    <string name="add_widget">Add widget</string>
Label to add a widget.

    <string name="BuilderTitle">Bluetooth Device</string>
This is the title of the list on Bluetooth devices when configuring the connect widget.

    <string name="ButtonString">Connect</string>
This is the default connect widget text string.

    <string name="Connecting">Connecting</string>
String shown when connecting a device.

    <string name="Disconnecting">Disconnecting</string>
String shown when disconnecting a device.

    <string name="InvalidDevice">Invalid Device</string>
String shown when there is an error of invalid device.

    <string name="NullDevice">Null Device</string>
String shown when there is an error of null device.

**Comment by ashed** [comment]
Hello @jroal.
I update ru translation in this branch:
https://github.com/jroal/a2dpvolume/blob/stringlate-ru-6762/app/src/main/res/values-ru/strings.xml

**Comment by uschindler** [comment]
I added the German strings.

**Comment by jroal** [comment]
I could not find French translator.  I used Google Translate for the new French strings for now.
