### ISSUE TITLE
tag for 2.13.0.4

### ISSUE THREAD

**Issue by leela52452** [jroal/a2dpvolume#284]
@jroal i noticed there are no tags or releases. 2.13.0.4 is google play version.
can you please update them.

**Comment by jroal** [comment]
done

**Comment by IzzySoft** [comment]
Thanks @jroal! Will you continue tagging versions (e.g. remember to tag each release)?

Reason for my question: I'm one of the F-Droid maintainers. Currently, we could not enable update check for your app as you didn't have any tags (sure there's `versionCode`/`versionName` in AndroidManifest – but it's hard to tell if that's increased at the begin or the end of the development cycle for a version, so we don't). Now you have – and tags are somehow reliable (they are always only created at release time). So if we know you will keep that up, it would enable us to keep your app updated much more in-time.
